"""Project-wide constants (e.g., CHUNK_SIZE, default ports)."""

CHUNK_SIZE_BYTES: int = 4 * 1024 * 1024

STREAM_PIECE_SIZE_BYTES: int = 64 * 1024

CONTROLLER_PORT: int = 8000
CHUNKSERVER_PORT: int = 50051

CHUNKSERVER_SERVICE_NAME: str = "chunkserver"
CONTROLLER_SERVICE_NAME: str = "controller"

CHUNKSERVER_TIMEOUT_SECONDS: int = 60
GRPC_KEEPALIVE_TIME_MS: int = 60000
GRPC_KEEPALIVE_TIMEOUT_MS: int = 10000

CHECKSUM_ALGORITHM: str = "sha256"

DEFAULT_CHUNK_STORAGE_PATH: str = "/app/data/chunks"
DEFAULT_CHUNK_INDEX_PATH: str = "/app/data/chunk_index.json"

REPLICATION_PORT: int = 8001
GOSSIP_INTERVAL_SECONDS: int = 2
ANTI_ENTROPY_INTERVAL_SECONDS: int = 30
